POST http://aw-presenca-api.herokuapp.com/discipline/create
Content-Type: application/json

{
  "name": "DisciplineTestNumberTwo",
  "descricao": "DisciplineDescriptionNumberTwo"
}
###

GET http://aw-presenca-api.herokuapp.com/discipline
Content-Type: application/json