POST http://aw-presenca-api.herokuapp.com/discipline/create
Content-Type: application/json

{
  "name": "DisciplineTestNumberOn2",
  "descricao": "DisciplineDescriptionNumberOne"
}
###

GET http://aw-presenca-api.herokuapp.com/discipline
Content-Type: application/json