POST http://aw-presenca-api.herokuapp.com/student/create
Content-Type: application/json

{
  "name": "NameTestSix",
  "email": "emailTestSix@gamil.com"
}

###

GET https://aw-presenca-api.herokuapp.com/student
Content-Type: application/json